RUN apt-get update && \
    apt-get install -y gnupg curl

#-----Descargar la clave GPG del repositorio de MongoDB y agregarla al sistema---------
RUN curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list
RUN apt-get update && apt-get install -y mongodb-org

EXPOSE 27017

RUN mkdir -p /data/db


RUN echo '#!/bin/bash\n\
mongod --dbpath /data/db --tlsMode preferTLS --tlsCertificateKeyFile server_combined.pem \n\
--tlsCAFile ca.crt --tlsAllowInvalidCertificates --bind_ip 0.0.0.0' > /start.sh && chmod +x /start.sh

# Comando por defecto para ejecutar el script
CMD ["/start.sh"]
