services:
  - type: web
    name: node-service
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: PATH_DB
        value: mongo

  - type: web
    name: mongo
    env: docker
    dockerfilePath: Dockerfile-Mongo
    plan: free
    autoDeploy: true
    dockerCommand: "--bind_ip_all"
