services:
  web:
    container_name: contendor_node
    restart: always
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - mongo #Ojo, se pone el nombre del servicio
    networks:
      - app-network 
    environment:
      - PATH_DB=mongo

  mongo:
    container_name: contenedor_mongodb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - C:/datosDocker:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  mydbdata:  # Aquí defines el volumen 'mydbdata'
